#!/bin/sh

crontab -l > /mycron

#echo "*/10 * * * * cd /app && python3 /app/youtube.py" >> /mycron
echo "0 10,14,18,22 * * * cd /app && python3 /app/mapianist.py
*/5 * * * * cd /app && python3 /app/check_google_home_mini.py" > /mycron

crontab /mycron
rm /mycron

/etc/init.d/cron start

crontab -l

tail -f /app/log.txt
